### ISSUE TITLE
Part of the Documentation is missing?

### ISSUE THREAD

**Issue by nan0m** [R3X-G1L6AME5H/FBIKM#1]
It looks like a really nice Plugin. It seems to me the readme.md is cut off for some reason?

**Comment by R3X-G1L6AME5H** [comment]
Your eyes aren't fooling you. Truth be told, this was a finals project of mine so the entire documentation is already written down. My problem is, however, twofold: it's way too damn long, AND it's in another language.

I'm a dev like any other; long documentations scare me 😅. That being said, I did swear to come back and finish it one day, it's just that I got wrapped up in all the other projects.

If you are considering using it... trust me, it's only worth looking at. Bloated, slow, and impractical; all things considered, the built-in Godot SkeletonIK node(which also uses FABRIK) is a much wiser choice for any Inverse Kinematics task. Another reason why I've been procrastinating in finishing the README. 

Otherwise, thanks for the interest. If you want to know how Fabrik works, you unfortunately won't be finding it here for the time being. It's a tough read but I recommend the original scientific paper. There should be a link in the README. 

Otherwise, do have a nice day. ✌️😁
